# Negação explícita para arquivos estáticos
[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.ico"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff2"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.ttf"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Redirecionar TODAS as outras rotas para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
